apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 1
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '5.3.0'
  licenseKeySecretName: <LICENSE-KEY-SECRET-NAME>
  jet:
    enabled: true
    resourceUploadEnabled: true
