apiVersion: hazelcast.com/v1alpha1
kind: JetJob
metadata:
  name: job-transaction-v1
spec:
  name: transaction-v1
  hazelcastResourceName: hazelcast
  state: Running
  jarName: jet-pipelines-1.0-SNAPSHOT.jar
  mainClass: org.examples.jet.snapshot.JobV1
  bucketConfig:
    bucketURI: gs://snapshot-tutorial
    secretName: gcp-sa
